# syntax=docker/dockerfile:1.7

FROM node:22-alpine AS build

WORKDIR /app

ARG PUBLIC_SITE_URL
ARG STRAPI_API_URL
ARG STRAPI_TOKEN
ARG CACHE_BUST   # 🔥 ADD THIS

ENV PUBLIC_SITE_URL=$PUBLIC_SITE_URL
ENV STRAPI_API_URL=$STRAPI_API_URL
ENV STRAPI_TOKEN=$STRAPI_TOKEN
ENV NODE_ENV=production

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

# 🔥 THIS LINE FORCES REBUILD
RUN echo "Cache bust: $CACHE_BUST"

RUN npm run build
